INFO [2025-07-18 15:24:54,658] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:25:57,203] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:26:22,826] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:26:24,406] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:26:27,742] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:26:28,147] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:40:34,387] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 15:40:35,025] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:36:20,870] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:37:24,726] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:39:35,200] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:41:30,062] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:41:30,815] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
ERROR [2025-07-18 16:47:48,277] [error_handler._log_error:193]: Hata: 'messages' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined


ERROR [2025-07-18 16:47:48,282] [error_handler._handle_general_error:273]: Hata: 'messages' is undefined
ERROR [2025-07-18 16:47:48,282] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined

ERROR [2025-07-18 16:47:50,955] [error_handler._log_error:193]: Hata: 'messages' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined


ERROR [2025-07-18 16:47:50,957] [error_handler._handle_general_error:273]: Hata: 'messages' is undefined
ERROR [2025-07-18 16:47:50,957] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined

ERROR [2025-07-18 16:47:51,824] [error_handler._log_error:193]: Hata: 'messages' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined


ERROR [2025-07-18 16:47:51,827] [error_handler._handle_general_error:273]: Hata: 'messages' is undefined
ERROR [2025-07-18 16:47:51,827] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined

INFO [2025-07-18 16:51:39,720] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:51:40,356] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:59:56,613] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 16:59:57,221] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
ERROR [2025-07-18 16:59:58,726] [error_handler._log_error:193]: Hata: 'messages' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined


ERROR [2025-07-18 16:59:58,727] [error_handler._handle_general_error:273]: Hata: 'messages' is undefined
ERROR [2025-07-18 16:59:58,727] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 41, in login
    return render_template('auth/login.html')
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 10, in block 'auth_form'
    <h4 class="fw-bold">{{ messages.form_title }}</h4>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'messages' is undefined

INFO [2025-07-18 17:01:54,418] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:05:19,500] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:12:13,386] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:13:36,668] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:13:37,330] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
ERROR [2025-07-18 17:13:43,132] [error_handler._log_error:193]: Hata: 'ui' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 54, in login
    return render_template('auth/login.html', messages=messages)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 29, in block 'auth_form'
    <label class="form-check-label" for="flexSwitchCheckChecked">{{ ui.get_message('auth.login.remember_me') }}</label>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ui' is undefined


ERROR [2025-07-18 17:13:43,136] [error_handler._handle_general_error:273]: Hata: 'ui' is undefined
ERROR [2025-07-18 17:13:43,138] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 54, in login
    return render_template('auth/login.html', messages=messages)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 29, in block 'auth_form'
    <label class="form-check-label" for="flexSwitchCheckChecked">{{ ui.get_message('auth.login.remember_me') }}</label>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ui' is undefined

INFO [2025-07-18 17:14:48,556] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:14:49,200] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
ERROR [2025-07-18 17:14:50,326] [error_handler._log_error:193]: Hata: 'ui' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 54, in login
    return render_template('auth/login.html', messages=messages)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 29, in block 'auth_form'
    <label class="form-check-label" for="flexSwitchCheckChecked">{{ ui.get_message('auth.login.remember_me') }}</label>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ui' is undefined


ERROR [2025-07-18 17:14:50,328] [error_handler._handle_general_error:273]: Hata: 'ui' is undefined
ERROR [2025-07-18 17:14:50,328] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 54, in login
    return render_template('auth/login.html', messages=messages)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 29, in block 'auth_form'
    <label class="form-check-label" for="flexSwitchCheckChecked">{{ ui.get_message('auth.login.remember_me') }}</label>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ui' is undefined

ERROR [2025-07-18 17:14:51,567] [error_handler._log_error:193]: Hata: 'ui' is undefined
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 54, in login
    return render_template('auth/login.html', messages=messages)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 29, in block 'auth_form'
    <label class="form-check-label" for="flexSwitchCheckChecked">{{ ui.get_message('auth.login.remember_me') }}</label>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ui' is undefined


ERROR [2025-07-18 17:14:51,567] [error_handler._handle_general_error:273]: Hata: 'ui' is undefined
ERROR [2025-07-18 17:14:51,569] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 54, in login
    return render_template('auth/login.html', messages=messages)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 1, in top-level template code
    {% extends "layouts/auth_layout.html" %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 66, in top-level template code
    {% block body %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\layouts\auth_layout.html", line 72, in block 'body'
    {% block auth_form %}
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\login.html", line 29, in block 'auth_form'
    <label class="form-check-label" for="flexSwitchCheckChecked">{{ ui.get_message('auth.login.remember_me') }}</label>
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ui' is undefined

INFO [2025-07-18 17:16:19,368] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:17:29,811] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:17:38,639] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:17:39,391] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:21:08,719] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:21:26,056] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:21:50,661] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:22:50,571] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:22:51,067] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:29:44,132] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 17:29:44,523] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 18:42:02,325] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 18:42:19,081] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 18:42:19,694] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 18:44:56,214] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 18:44:56,961] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:25:39,253] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:28:34,836] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:28:35,716] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:36:42,747] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:36:43,231] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:42:50,368] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:42:50,964] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
ERROR [2025-07-18 19:43:35,066] [error_handler._log_error:193]: Hata: Encountered unknown tag 'endblock'.
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 50, in register
    return self.ui_service.render_auth_page('register')
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 131, in render_auth_page
    return self.render_template(f"auth/{page_type}", data)
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 102, in render_template
    return render_template(f"{template_name}.html", **data)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\register.html", line 145, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.


ERROR [2025-07-18 19:43:35,068] [error_handler._handle_general_error:273]: Hata: Encountered unknown tag 'endblock'.
ERROR [2025-07-18 19:43:35,068] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 50, in register
    return self.ui_service.render_auth_page('register')
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 131, in render_auth_page
    return self.render_template(f"auth/{page_type}", data)
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 102, in render_template
    return render_template(f"{template_name}.html", **data)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\register.html", line 145, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.

INFO [2025-07-18 19:43:48,711] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:43:49,309] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
ERROR [2025-07-18 19:43:51,331] [error_handler._log_error:193]: Hata: Encountered unknown tag 'endblock'.
Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 50, in register
    return self.ui_service.render_auth_page('register')
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 131, in render_auth_page
    return self.render_template(f"auth/{page_type}", data)
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 102, in render_template
    return render_template(f"{template_name}.html", **data)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\register.html", line 145, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.


ERROR [2025-07-18 19:43:51,331] [error_handler._handle_general_error:273]: Hata: Encountered unknown tag 'endblock'.
ERROR [2025-07-18 19:43:51,331] [error_handler._handle_general_error:274]: Traceback:
Traceback (most recent call last):
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\wamp64\www\yedekler\PofuAi\app\Controllers\AuthController.py", line 50, in register
    return self.ui_service.render_auth_page('register')
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 131, in render_auth_page
    return self.render_template(f"auth/{page_type}", data)
  File "C:\wamp64\www\yedekler\PofuAi\core\Services\UIService.py", line 102, in render_template
    return render_template(f"{template_name}.html", **data)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ilker\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\wamp64\www\yedekler\PofuAi\public\Views\auth\register.html", line 145, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.

INFO [2025-07-18 19:45:52,304] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:45:52,829] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:52:11,894] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:52:12,427] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:56:37,601] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:56:38,205] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:59:28,419] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 19:59:28,995] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:03:40,971] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:03:41,568] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:08:38,817] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:08:39,471] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:33:00,251] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:33:01,030] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:37:42,753] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:38:38,503] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:39:08,460] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:40:00,436] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:40:02,380] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:40:15,850] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:40:16,665] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:44:31,818] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:45:51,259] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:45:52,213] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:47:24,274] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 20:47:25,104] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 21:58:22,121] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: c:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:11:38,615] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:12:39,575] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:12:40,116] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:13:51,547] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:19:35,315] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:19:35,859] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:36:13,324] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:37:29,504] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:38:01,174] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:38:14,984] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:38:59,547] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:39:00,426] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:41:16,651] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:41:28,741] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:41:36,030] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:41:36,959] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 22:57:27,125] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:07:57,657] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:13:38,875] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:14:23,091] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:18:23,058] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:18:50,857] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:19:06,521] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
INFO [2025-07-18 23:19:30,317] [logger.init:101]: Logger baþlatýldý - Seviye: DEBUG, Dosya: C:\wamp64\www\yedekler\PofuAi\storage\logs\app_2025-07-18.log
